# Generated by Django 5.0 on 2024-02-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
